<?php
DEFINE("CONDOLANCE_TRANS","condolance_trans",true); 
DEFINE("COURSE_MASTER","course_master",true); 
DEFINE("DIVISION_MASTER","division_master",true); 
DEFINE("GRADUATION_MASTER","graduation_master",true); 
DEFINE("HOLIDAY_MASTER","holiday_master",true); 
DEFINE("OD_DESC_MASTER","od_desc_master",true); 
DEFINE("OD_TRANS","od_trans",true); 
DEFINE("OD_TRANS_DETAILS","od_trans_details",true); 
DEFINE("SEMESTER_MASTER","semester_master",true); 
DEFINE("STAFF_MAPPING","staff_mapping",true); 
DEFINE("STAFF_MASTER","staff_master",true); 
DEFINE("USER_TYPE","user_type",true); 
DEFINE("YEAR_MASTER","year_master",true); 
DEFINE("ATTTENDANCE_TRANS","atttendance_trans",true); 
DEFINE("COURSE_REG","course_reg",true); 
DEFINE("COURSE_REG_DETAILS","course_reg_details",true); 
DEFINE("DEPT_MASTER","dept_master",true); 
DEFINE("SUBJECT_MASTER","subject_master",true); 
?>